name: Dump
 
on:
  push:
    branches: [ main ]

env:
  ROM_URL: https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS2.0.11.0.VNGMIXM/sapphire_global-ota_full-OS2.0.11.0.VNGMIXM-user-15.0-c9b31d1dfe.zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v3

       - name: Setup Dump Environment
         run: |
              sudo apt update -y && sudo apt upgrade -y
              sudo apt install unace python3 unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract device-tree-compiler liblzma-dev python3-pip python3-setuptools brotli liblz4-tool axel gawk aria2 detox cpio rename -y
              pip3 install pip setuptools wheel -U
              pip3 install backports.lzma protobuf pycrypto docopt zstandard twrpdtgen

       - name: Running Dumpyara Shell Script
         run: |
              bash .github/workflows/dumpyara.sh "$ROM_URL"

       - name: Checking Folder
         run: |
              cd /home/runner/work/AndroidDumpsCI/AndroidDumpsCI/.github/workflows/working/
              ls -la

       - name: Compressing with tar.xz
         run: |
              cd /home/runner/work/AndroidDumpsCI/AndroidDumpsCI/.github/workflows/working/
              tar c /home/runner/work/AndroidDumpsCI/AndroidDumpsCI/.github/workflows/working/* | nice -n19 xz -9 -T4 > dump.tar.xz

       - name: Store Generated Files
         uses: actions/upload-artifact@v3
         with:
           path: /home/runner/work/AndroidDumpsCI/AndroidDumpsCI/.github/workflows/working/dump.tar.xz
           if-no-files-found: error
